[build]
builder = "NIXPACKS"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs-20_x"]

[build.nixpacksPlan.phases.install]
cmds = ["npm ci --omit=dev"]

[build.nixpacksPlan.phases.build]
cmds = ["npm run build"]

[deploy]
startCommand = "npm run start"