[build]
builder = "NIXPACKS"
buildCommand = "npm ci --omit=dev --legacy-peer-deps && npm run build"

[deploy]
startCommand = "npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
NIXPACKS_NODE_VERSION = "18"
